name: Deploy on Push to Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.10.0'

      - name: Set Git Config
        run: |
          git config --global user.email "brendanngjj@gmail.com"
          git config --global user.name "brendanng7"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Build the Project
        run: pnpm next build

      - name: Prepare Deployment
        run: |
          touch out/.nojekyll
          git add out/
          git commit -m "Deploy"

      - name: Fetch gh-pages
        run: git fetch origin gh-pages

      - name: Push to gh-pages
        run: git subtree push --prefix out origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
